### ISSUE TITLE
Error on installing the Laravel-Leaderboard

### ISSUE THREAD

**Issue by AqibTeam** [faustbrian/Laravel-Leaderboard#15]
Hi,
I am tring to install the package on my Laravel v5.5.40, but the composer return me this error.

domain@hl361:~/www$ ../composer.phar require faustbrian/laravel-leaderboard
Using version ^1.1 for faustbrian/laravel-leaderboard
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for faustbrian/laravel-leaderboard ^1.1 -> satisfiable by faustbrian/laravel-leaderboard[1.1.0].
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - faustbrian/laravel-leaderboard 1.1.0 requires illuminate/database 5.3.* || 5.4.* -> satisfiable by illuminate/database[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/database 5.3.x-dev|don't install laravel/framework v5.5.40
    - don't install illuminate/database 5.4.x-dev|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.3.0|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.3.16|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.3.23|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.3.4|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.13|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.17|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.19|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.27|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.36|don't install laravel/framework v5.5.40
    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.5.40
    - Installation request for laravel/framework (locked at v5.5.40, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.40].
Installation failed, reverting ./composer.json to its original content. 

Please can you help to solve this problem.

Thanks

**Comment by chrisidakwo** [comment]
Simple. You're using a higher version of Laravel. I know this is old, but ...

**Comment by AqibTeam** [comment]
Ok, thanks
