### ISSUE TITLE
Extending for usage with Redis (etc)

### ISSUE THREAD

**Issue by maximusblade** [faustbrian/Laravel-Leaderboard#2]
# This is more of an enhancement.

I think extending this to be able to use something like Redis would be awesome.
but thats an enhancement.
Im hoping to find time soon to work on something like that.

**Comment by DraperStudio** [comment]
Send a PR if you have time.  I don't have the time to add this at the moment.
--
Sent from myMail app for Android Wednesday, 25 May 2016, 11:24a.m. +02:00 from maximusblade  notifications@github.com :
